version: "3.3"
services:
  mailbox:
    build:
      context: ./mailbox
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailbox.rule=Host(`mailbox.wormhole.bryanchriswhite.com`)"
      - "traefik.http.routers.mailbox.entrypoints=websecure"
      - "traefik.http.routers.mailbox.tls.certresolver=mytlschallenge"

  relay:
    build:
      context: ./relay
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.relay.rule=Host(`relay.wormhole.bryanchriswhite.com`)"
      - "traefik.http.routers.relay.entrypoints=websecure"
      - "traefik.http.routers.relay.tls.certresolver=mytlschallenge"

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=admin@bryanchriswhite.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

#  whoami:
#    image: "containous/whoami"
#    container_name: "simple-service"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.whoami.rule=Host(`mailbox.wormhole.bryanchriswhite.com`)"
#      - "traefik.http.routers.whoami.entrypoints=websecure"
#      - "traefik.http.routers.whoami.tls.certresolver=mytlschallenge"