- id: redeploy-webhook
  execute-command: "./scripts/deploy.sh"
  command-working-directory: "/etc/webhook"
  pass-arguments-to-command:
    - source: payload
      name: "release.tag_name"
    - source: header
      name: "X-Hub-Signature-256"
    - source: entire-payload
