- id: release
  execute-command: "./docker/hooks/scripts/release.sh"
  command-working-directory: "/etc/webhook"
  pass-arguments-to-command:
    - source: payload
      name: "release.tag_name"
  trigger-rule:
    and:
      - match:
        type: payload-hmac-sha256
        secret: "{{ getenv "GITHUB_WEBHOOK_KEY" | js }}"
        parameter:
          source: header
          name: "X-Hub-Signature-256"
      - match:
        type: value
        value: published
        parameter:
          source: payload
          name: action
#- id: master
#  execute-command: "./docker/hooks/scripts/master.sh"
#  command-working-directory: "/etc/webhook"
#  pass-arguments-to-command:
#    - source: payload
#      name: "release.tag_name"
#    - source: string
#      name: "s3://test.winden.la.bryanchriswhite.com"
#    - source: string
#      name: "E37U3141WQ4OZX"
#  trigger-rule:
#    and:
#      - match:
#        type: payload-hmac-sha256
#        secret: "{{ getenv "GITHUB_WEBHOOK_KEY" | js }}"
#        parameter:
#          source: header
#          name: "X-Hub-Signature-256"
#      - match:
#        type: value
#        value: published
#        parameter:
#          source: payload
#          name: action
