name: transfer-repo-CI
on: [push, pull_request]
jobs:

  build:
    name: Build/Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 4
    strategy:
      matrix:
        go-version: [1.16.2]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup npm, yarn etc.
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install yarn
        run: npm install yarn@1.22.10
        id: node

      - name: install yarn dependencies
        run: yarn install

      - name: setup Go toolchain
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: build wasm code
        run: yarn build:wasm

      - name: run tests
        run: yarn test:unit
