# GITHUB actions disabled as repository is not maintained.

# name: transfer-repo-CI
# on: [push, pull_request]
# jobs:
#   build:
#     name: Build/Test
#     runs-on: ${{ matrix.os }}
#     timeout-minutes: 10
#     strategy:
#       matrix:
#         go-version: [1.16.2]
#         os: [ubuntu-latest]
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#         with:
#           # Checkout head of the branch of the PR, or the exact revision
#           # specified for non-PR builds.
#           ref: "${{ github.event.pull_request.head.sha || github.sha }}"

#       - name: checkout and update submodules
#         run: git submodule update --init --recursive

#       - name: setup npm, yarn etc.
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'

#       - name: Install yarn
#         run: npm install yarn@1.22.10
#         id: node

#       - name: install yarn dependencies
#         run: yarn install

#       - name: setup Go toolchain
#         uses: actions/setup-go@v1
#         with:
#           go-version: ${{ matrix.go-version }}

#       - name: build wasm code
#         run: yarn build:wasm

#       - name: setup python
#         uses: actions/setup-python@v2

#       - name: install mailbox server
#         run: pip install magic-wormhole-mailbox-server

#       - name: install relay server
#         run: pip install git+https://github.com/magic-wormhole/magic-wormhole-transit-relay.git

#       - name: run mailbox server
#         run: twist wormhole-mailbox --usage-db=usage.sqlite &

#       - name: run transit relay
#         run: twist transitrelay --port=tcp:4001 --websocket=tcp:4002 &

#       - name: run tests
#         run: yarn test:unit

#       - name: lint the code
#         run: yarn lint

#       - name: build the playground site
#         run: |
#           cat <<EOF >> .playground.build.env
#           STAGE_HOSTNAME="https://localhost:8080"
#           STAGE_MAILBOX_URL="wss://localhost:4000/v1"
#           STAGE_RELAY_URL="wss://localhost:4002"
#           EOF
#           yarn build:playground

#       - name: build the production site
#         run: |
#           rm -rf ./dist
#           cat <<EOF >> .production.build.env
#           STAGE_HOSTNAME="https://localhost:8080"
#           STAGE_MAILBOX_URL="wss://localhost:4000/v1"
#           STAGE_RELAY_URL="wss://localhost:4002"
#           EOF
#           yarn build:production
